feat: add aws lambda integration with sentry
cultureamp/ca-go pull request #16
Opened 2022-03-22 22:26 UTC by aimeegee

2022-03-23 01:01 UTC, jamestelfer reviewed
As very general comments:

- we need to look at the names we've used here and make sure they make sense in this context. For example, we should look at `LambdaHandler` instead of `Handler`, and `Options` is probably too generic as well.
- the documentation on any public methods is really important for this repo
- Let's try to include a couple of `Example` tests where we can, as they become a really practical (and living) part of the documentation.

2022-03-23 01:11 UTC, jamestelfer commented
Useful doco: https://docs.aws.amazon.com/lambda/latest/dg/golang-handler.html

2022-03-23 04:00 UTC, aimeegee commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Sentry exception monitoring (via ca-go) to the FusionAuth hooks lambdas](https://trello.com/c/u0c0YzDw/927-add-sentry-exception-monitoring-via-ca-go-to-the-fusionauth-hooks-lambdas)

2022-03-24 21:57 UTC, jamestelfer approved these changes

2022-03-24 23:24 UTC, disposedtrolley requested changes
Looks good! Generics seem pretty tame in Go, and very useful in this context.

I have some minor suggestions and a nitpick, but really happy with this change.

2022-03-24 23:24 UTC, disposedtrolley commented on x/sentry/errorreport/lambda.go
> +		afterHandler(ctx, err)
Do we need separate before and after handlers, or can we report the error in the beforeHandler?

Any context mutations performed by the nextHandler won't be propagated to the afterHandler.

2022-03-24 23:24 UTC, disposedtrolley commented on x/sentry/errorreport/lambda_example_test.go
> +		}
```suggestion
		if err := processRecord(ctx, record); err != nil {
			return err
		}
```

nitpick

2022-03-25 00:39 UTC, aimeegee commented on x/sentry/errorreport/lambda.go
> +		afterHandler(ctx, err)
We can't handle the error in beforeHandler like this until it's returned by nextHandler() right? So if we wanna merge beforeHandler and afterHandler, does that mean we gonna end up with:
```
out, err := nextHandler(ctx, event)
defer afterHandler(ctx, options, err) // doing error reporting and panic handling here
```
Would that cause any panic being missed...?

2022-03-25 00:41 UTC, disposedtrolley commented on x/sentry/errorreport/lambda.go
> +		afterHandler(ctx, err)
Ahh yeah, I'm not sure how I missed that!

2022-03-25 00:41 UTC, disposedtrolley approved these changes

2022-03-25 00:51 UTC, merged

2022-03-25 01:17 UTC, jamestelfer commented on x/sentry/errorreport/lambda.go
> +		afterHandler(ctx, err)
Marking this as resolved: the current state is correct AFAICT