Add flags package
cultureamp/ca-go pull request #4
Opened 2021-11-17 03:25 UTC by disposedtrolley

2021-11-18 22:49 UTC, disposedtrolley commented
![](https://github.trello.services/images/mini-trello-icon.png) [Wrap SDK for Golang (ca-go/flags)](https://trello.com/c/XOxGYWlx/715-create-ca-go-flags)

2021-11-22 04:31 UTC, jamestelfer requested changes
Thanks for putting up a draft so quickly to get some conversation going.

At a high level, while functional, it does seem to leak a lot of "LaunchDarkly"ness through the config.

There's a couple of ways of looking at this. One is that if we were to have a different provider, we'd change (and then major version) the API.

Another way might be to expose a `flags.Client` interface, and keep the config in a different package. There are strengths and weaknesses in either case.

For a final version, we'd like to have a `doc.go` for the package docs, and some `Example` style tests showing the usage. I can see why you haven't done them yet though.

2021-11-22 04:31 UTC, jamestelfer commented on x/flags/flags_test.go
> +	t.Run("allows daemon mode to be configured with an alterate Dynamo base URL", func(t *testing.T) {
```suggestion
	t.Run("allows daemon mode to be configured with an alternate Dynamo base URL", func(t *testing.T) {
```

2021-11-22 04:31 UTC, jamestelfer commented on x/flags/flags.go
> +func NewClient(opts ...ConfigOption) (*Client, error) {
If we expose the `Client` struct here, how would we introduce a different implementation do you think?

2021-11-22 04:31 UTC, jamestelfer commented on x/flags/flags.go
> +func WithDaemonMode(dynamoTableName string, cacheTTL time.Duration) ConfigOption {
These configuration options are basically LaunchDarkly. How worried are we about a different implementation?

2021-11-22 04:31 UTC, jamestelfer commented on x/flags/flags.go
> +func (c *Client) Connect() error {
WDYT about putting the `Client` struct and methods in a separate file to the config implementation?

2021-11-22 04:31 UTC, jamestelfer commented on x/flags/flags.go
> +func (c *Client) RawClient() *ld.LDClient {
If we were to change the implementation, this method would be a liability. Perhaps the return type should be `interface{}`.

I like the ethos of adding an escape hatch, but we should avoid branding it 😄

2021-11-22 23:35 UTC, disposedtrolley commented on x/flags/flags.go
> +func (c *Client) Connect() error {
Yep that's a great idea -- I kept them both in the same file in this first pass as I was constantly referring between the two structs.

2021-11-22 23:37 UTC, disposedtrolley commented on x/flags/flags.go
> +func (c *Client) RawClient() *ld.LDClient {
I agree. We can stipulate in the documentation that `RawClient()` should be used at your own risk, and the need to cast from an interface to `*ld.LDCLient` provides a nice hoop that users will need to jump through.

2021-11-22 23:52 UTC, disposedtrolley commented on x/flags/flags.go
> +func NewClient(opts ...ConfigOption) (*Client, error) {
I was considering declaring `Client` as an interface (which is what I had in the [flags package for the PoC](https://github.com/cultureamp/employee-tasks-service/blob/4426310d0673b8b1998b8a47e1da9474b921583e/src/flags/flags.go#L119-L124) but it felt like another layer of indirection that doesn't provide much value.

I wanted to rely on Go's consumer-driven interfaces here so we can provide a slimmer library overall. Consumers of the library can use their own interface type that expose the portions of `Client` that they're interested in using. What do you think of this approach?

2021-11-23 00:03 UTC, disposedtrolley commented on x/flags/flags.go
> +func WithDaemonMode(dynamoTableName string, cacheTTL time.Duration) ConfigOption {
I'm not worried for the foreseeable future, but I definitely get your concern.

My initial goals with the wrappers wasn't to insulate LaunchDarkly's API surface from our services, but to provide a more convenient and standardised way of configuring and using their methods. We can probably reduce the coupling somewhat by abstracting the ideas of configuration and the client, but I'm worried that makes for a more confusing library and it feels like premature abstraction.

I sketched out what this package might look like if we provided more interfaces:

```go
type LDConfigOption func(c *LDClient)

type LDConfig struct {...}

func NewLDConfig(opts ...LDConfigOption) LDConfig {...}

type Client interface {
    Query(...)
    Shutdown()
    Connect()
}

type LDClient struct {...}

func NewLDClient(cfg LDConfig) Client {...}

func (c *LDClient) Query(...) {...}
func (c *LDClient) Shutdown() {...}
func (c *LDClient) Connect() {...}


func main() {
    config := NewLDConfig(...)
    client := NewLDClient(config)

    client.Query(...)
}
```

2021-11-29 03:33 UTC, disposedtrolley commented
Once we're happy with the API and implementation, I'll fix up the commit history.

2021-12-01 07:17 UTC, hallaji reviewed
I think we need to come up with a consistent interface across different wrappers, e.g. what sort of user object/interface are we exposing to developers? It could be documented somewhere as a reference. What do you think?

2021-12-01 07:17 UTC, hallaji commented on x/launchdarkly/flags/user.go
> +	ldUser lduser.User
I wonder whether we plan to expose entire LD user object or not? How about destructing the object here one by one and adding those that will be needed? That's gonna hide LD user struct as well.

2021-12-02 22:13 UTC, melm73 submitted a review, later dismissed

2021-12-02 22:13 UTC, melm73 commented on x/launchdarkly/flags/user.go
> +	userAttributeRealUserAggregateID = "realUserAggregateID"
Same comment as the other wrappers, can we please not use `aggregate` in our field names. Within the monoliths we have the problem of multiple ids for these domains, but outside the monolith there is no need to make this distinction. There is only 1 id that we care about for accounts and users.

The JWT is a good example of this. No `aggregate` in sight.

(Side note... accounts are not even event sourced, so actually it isn't an aggregate id at all 😜 )

2021-12-02 22:15 UTC, disposedtrolley commented
> I think we need to come up with a consistent interface across different wrappers,

Yes that's a great idea. We should keep the interface loose so it can be adapted to suit each language, but the overall concepts and usage patterns should be similar.

What I've been doing for the Ruby and Go wrappers is offering two ways of configuring and instantiating the client:

- As an internally managed singleton where the application can configure some globals during initialisation, and retrieve the singleton instance from the package at the time of use.
- A regular constructor that returns an instance of the client, that the application must manage itself.

Both approaches have two stages:

1. Configuration: options are specified in some manner and passed into the appropriate function depending on the approach above.
2. Connection: a connection to LaunchDarkly is established.
3. Usage: methods on the client instance are called (or the singleton is retrieved and methods on it are called).
4. Shutdown: the client provides a Shutdown method that closes connections to LaunchDarkly.

2021-12-02 22:15 UTC, disposedtrolley commented on x/launchdarkly/flags/user.go
> +	ldUser lduser.User
The LD user and client objects are provided as an escape hatch as we're not wrapping the entirety of the interface.

2021-12-02 22:16 UTC, disposedtrolley commented on x/launchdarkly/flags/user.go
> +	userAttributeRealUserAggregateID = "realUserAggregateID"
Yeah I've been meaning to change these, thanks for reminding me!

2021-12-23 05:23 UTC, aimeegee approved these changes
Great work James. I'll take yours as a model when adding other packages in

2021-12-23 06:43 UTC, merged