add devbox
cultureamp/ca-go pull request #435
Opened 2024-06-07 00:47 UTC by elliotthilaire-ca

- **Remove .envrc from .gitignore**
- **Run `devbox generate direnv`**
- **Add devbox.json**
- **Devbox add pre-commit, snyk, trufflehog**
- **Exclude devbox.json from check-json commit hook**
- **Update README.md with instructions for setting up with devbox.**
- **Remove .devcontainer config**

2024-06-07 02:11 UTC, t-monaghan commented on .gitignore
> -.envrc
If `.envrc` was previously ignored, should we include some guidance in the readme to reflect how to handle environment secrets?

2024-06-07 02:19 UTC, t-monaghan requested changes
We discussed the issue of go modules from a devbox project existing outside of the project's isolation. My gut instinct is that this is fine, devbox itself is a go project, and if this was an issue I'm confident that the developers at Jetify would have addressed this with a default plugin. My other thought is that we should not look for a solution where we haven't had a problem yet, I'd be more inclined to solve it when we come across an issue, but it is worth some discovery.

2024-06-07 02:19 UTC, t-monaghan commented on .gitignore
> -.envrc
If .envrc was previously ignored, should we include some guidance in the readme to reflect how to handle environment secrets?

2024-06-07 02:19 UTC, t-monaghan commented on devbox.json
> +      "setup": "make mod",
Seeing as all `make` commands have phony targets can we fold these into devbox scripts?

2024-07-04 00:40 UTC, elliotthilaire-ca commented on .gitignore
> -.envrc
I've handled this here with a comment in the .envrc file. If anyone has a modified .envrc file that was private this explanation will show up when they bring in the new changes.
https://github.com/cultureamp/ca-go/pull/435/commits/5c3c51d6a37503266b5146f58f7bc97f31a4cb0e

Devs can create .env.local file that is .gitignored.  This approach allows overrides to be created while also being secure in that direnv allow is required to run when things are modified. More detail in the comment in .envrc.

2024-07-04 00:47 UTC, elliotthilaire-ca commented on devbox.json
> +      "setup": "make mod",
I decided against doing this.

Devbox is going to be the easiest way to set up the project but I don't want to make it difficult for anyone actively chooses to take a different route. Something like running tests is a 'project' concern rather than a 'setup project with devbox' concern.  If we move all commands into the devbox.json file then we make it harder for anyone who chooses not to use devbox.

2024-07-12 01:41 UTC, andrewcameronsims approved these changes

2024-07-12 01:54 UTC, merged