feat: add request package
cultureamp/ca-go pull request #6
Opened 2021-11-25 05:24 UTC by disposedtrolley

This PR adds a `request` package exposing types and helper functions to create, add, and retrieve request-scoped attributes to context.Context.

There are two sets of attributes that can be unique per request:

- Request identifiers like the trace, correlation, and request IDs.
- User identifiers like their account and user IDs, for authenticated requests.

2021-11-25 06:26 UTC, jamestelfer commented on request/requestids.go
> +	TraceID       string `json:"trace_id"`
What is the trace ID tracking? Could these be used in a context like an event (i.e. is the request nomenclature correct)? Are JSON tags really required here?

2021-11-25 06:55 UTC, disposedtrolley commented on request/requestids.go
> +	TraceID       string `json:"trace_id"`
@melm73 and I explored several options for naming the package, and `request` seemed the most natural. The original implementation was named `context`, and users were aliasing the import to `gcontext` which didn't seem ideal.

1. I think this is populated with the AWS XRay ID by request middleware.
2. Yeah they could. We tossed up between a few names and "request" seems to cover the breadth of architectures we might use this for.
3. I took them out but popped them back as I thought they might be used for logging. Maybe not...

2021-11-26 03:06 UTC, jamestelfer commented on request/requestids.go
> +func NewRequestIDs(traceID string, requestID string, correlationID string) RequestIDs {
Do we need a constructor method for this struct?

2021-11-26 04:43 UTC, disposedtrolley commented on request/requestids.go
> +func NewRequestIDs(traceID string, requestID string, correlationID string) RequestIDs {
I reckon we should have one to disambiguate whether pointer or value semantics should be used for `RequestIDs`.

2021-11-26 12:16 UTC, jamestelfer commented on request/requestids.go
> +	TraceID       string `json:"trace_id"`
(1) I'm not certain this still makes sense. Let's take it out and add it back if needed.
(2) As long as it's considered, I'm happy.
(3) Let's take them out and add them back if they're required.

2021-11-26 12:22 UTC, jamestelfer requested changes
Minor changes, but a good and clean first cut.

Let's add some examples for docs and get this in, and add the middleware later.

Question: `/x` prefix? I suppose this is currently pre-v1, so we might be OK?

2021-11-26 12:22 UTC, jamestelfer commented on request/user_test.go
> +func TestContextWithAuthenticatedUser(t *testing.T) {
Let's add some `Example*` methods in

2021-11-26 12:22 UTC, jamestelfer commented on request/doc.go
> +// account and user aggregate IDs can also be added to the context.
```suggestion
// The request package exposes types and helper methods to create, add, and retrieve
// request-scoped attributes to context.Context.
//
// Request-scoped attributes include identifiers like the request, trace, and
// correlation IDs. When the request is authenticated, user identifiers like the
// account and user aggregate IDs can also be added to the context.
```

2021-11-26 12:22 UTC, jamestelfer commented on request/requestids_test.go
> +func TestContextWithRequestIDs(t *testing.T) {
Examples?

2021-11-26 12:22 UTC, jamestelfer commented on request/user.go
> +const authenticatedUserKey = contextValueKey("payload")
```suggestion
const authenticatedUserKey = contextValueKey("authenticatedUser")
```

2021-11-28 23:14 UTC, disposedtrolley commented on request/doc.go
> +// account and user aggregate IDs can also be added to the context.
I've fixed the missing space, but I'm inclined to keep `Package request...` at the beginning of the doc. This appears to be the Go convention for package docs:

- https://pkg.go.dev/net/http#pkg-overview
- https://pkg.go.dev/encoding/gob#pkg-overview
- https://pkg.go.dev/github.com/stretchr/testify/assert?utm_source=godoc#pkg-overview

What are your thoughts?

2021-11-28 23:26 UTC, disposedtrolley commented
> Question: `/x` prefix? I suppose this is currently pre-v1, so we might be OK?

Yeah I think we should nest this under `/x` for now. It can graduate once we've migrated one or two applications to use this package.

2021-11-29 22:08 UTC, jamestelfer commented on request/requestids.go
> +func NewRequestIDs(traceID string, requestID string, correlationID string) RequestIDs {
What benefit do we gain from this unless there are methods?

2021-11-29 22:09 UTC, jamestelfer commented on request/doc.go
> +// account and user aggregate IDs can also be added to the context.
TIL, love the response. Keep it, and perhaps note it in the design.md?

2021-11-30 02:24 UTC, jamestelfer requested changes
A couple of points of discomfort in a generally awesome PR>

2021-11-30 02:24 UTC, jamestelfer commented on x/request/user.go
> +	EffectiveUserAggregateID string
```suggestion
	CustomerAccountID       string
	UserID string
	RealUserID      string
```

I don't think adding `Aggregate` in here is helpful. For JWT auth, that's what they're going to be set to, but I'm not convinced it should be part of the field name.

2021-11-30 02:24 UTC, jamestelfer commented on x/request/user.go
> +func NewAuthenticatedUser(accountAggregateID, realUserAggregateID, effectiveUserAggregateID string) AuthenticatedUser {
Same here regarding the constructor.

2021-11-30 02:24 UTC, jamestelfer commented on x/request/requestids.go
> +func NewRequestIDs(requestID string, correlationID string) RequestIDs {
To add to this, the two IDs are strings, and without named parameters this code becomes more prone to errors. I know Goland puts names in, but that's an IDE specific helper that kind of exposes the issue.

2021-11-30 02:24 UTC, jamestelfer commented on x/request/requestids_test.go
> +func ExampleContextWithRequestIDs() {
Love examples

2021-11-30 02:24 UTC, jamestelfer commented on x/request/user_test.go
> +func TestContextHasAuthenticatedUserSuceeds(t *testing.T) {
Seems like a method that could have an example too?

2021-11-30 02:40 UTC, disposedtrolley commented on x/request/requestids.go
> +func NewRequestIDs(requestID string, correlationID string) RequestIDs {
> I'd prefer to avoid constructor methods unless necessary.

Since this is serving as a bag of data with no methods I'm happy to remove it.

For more complex structs with methods (that can have pointer _or_ value receivers), it can be useful to denote its usage semantics with a constructor. If the constructor returns a pointer, the reader can expect a degree of mutability for instance.

2021-11-30 02:45 UTC, disposedtrolley commented on x/request/user.go
> +	EffectiveUserAggregateID string
I'm happy with the shorter names; I wasn't sure how useful being explicit with `aggregate` would be.

2021-11-30 02:47 UTC, disposedtrolley commented on x/request/user_test.go
> +func TestContextHasAuthenticatedUserSuceeds(t *testing.T) {
Yup could be useful. I'll add the equivalent for RequestIDs too.

2021-11-30 02:55 UTC, disposedtrolley commented on x/request/user.go
> +	EffectiveUserAggregateID string
Would it make sense to use the same names as web gateway? https://github.com/cultureamp/web-gateway/blob/ccf9db2fabb2a798a9905475a3fce63fdc192811/identity/identity.go#L20-L24

2021-11-30 02:59 UTC, jamestelfer commented on x/request/user.go
> +	EffectiveUserAggregateID string
That is what's exposed in the JWT. I'd follow that _except_ for `EffectiveUserID` becomes `UserID`. Every single time I see `Effective` and `Real` I have to ask myself which one I'm going to use. Even `Real` is ambiguous.

`UserID` and `ImpersonatingUserID` might be better.

2021-11-30 03:01 UTC, jamestelfer commented on x/request/requestids.go
> +func NewRequestIDs(requestID string, correlationID string) RequestIDs {
Note that a struct should generally have only one or the other, and the receiver type of any methods show the expected use.

2021-11-30 03:34 UTC, disposedtrolley commented on x/request/user.go
> +	EffectiveUserAggregateID string
Yeah, `Real` is only real in context. Would `ImpersonatingUserID` be the ID of the person who is impersonating, or being impersonated?

Naming is hard.

2021-11-30 03:34 UTC, disposedtrolley commented on x/request/user.go
> +	EffectiveUserAggregateID string
I'm also happy to keep it as `AccountID`, `UserID`, and `RealUserID` to be consistent with other systems for now.

2021-11-30 03:35 UTC, disposedtrolley commented on x/request/requestids.go
> +func NewRequestIDs(requestID string, correlationID string) RequestIDs {
True, but I think a constructor makes that more explicit.

2021-11-30 06:31 UTC, jamestelfer commented on x/request/user.go
> +	RealUserID        string
```suggestion
	// CustomerAccountID is the ID of the currently logged in user's parent account/organization, sometimes known as the "account_aggregate_id".
	CustomerAccountID string
	// UserID is the ID of the currently authenticated user, and will generally be a "user_aggregate_id".
	UserID            string
	// RealUserID, when supplied, is the ID of the user who is currently impersonating the current "UserID".
	// This value is optional.
	RealUserID        string
```

2021-12-02 22:39 UTC, jamestelfer approved these changes
Lets go!

2021-12-02 22:45 UTC, merged