feat: add Sentry package
cultureamp/ca-go pull request #7
Opened 2021-11-26 04:40 UTC by disposedtrolley

2021-11-26 05:17 UTC, hughevans commented on go.mod
> +	github.com/getsentry/sentry-go v0.11.0
You might like to add excludes for all the frameworks that `getsentry/sentry-go` pulls in because we know there’s CVEs in some of those. eg. https://github.com/cultureamp/glamplify/pull/39/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R37-R42

2021-11-26 05:23 UTC, hughevans commented on go.mod
> +	github.com/getsentry/sentry-go v0.11.0
More info here https://github.com/getsentry/sentry-go/issues/156

2021-11-26 05:42 UTC, disposedtrolley commented on go.mod
> +	github.com/getsentry/sentry-go v0.11.0
Thanks Hugh, I'll have a look!

2021-11-29 00:04 UTC, disposedtrolley commented on x/sentry/errorreport/middleware.go
> +	})
@jamestelfer do we need to append the user and request attributes to the Sentry scope here too? I noticed it was being done explicitly for the Goa middleware which calls our `ReportError` function.

2021-11-29 02:57 UTC, disposedtrolley commented on x/sentry/errorreport/middleware_test.go
> +package errorreport_test
I'm not sure if we need example tests here. There'd be a fair bit of boilerplate in the setup, and I'm unsure what we'd use for the output.

2021-11-29 03:21 UTC, disposedtrolley commented on x/sentry/errorreport/middleware_test.go
> +func TestGoaEndpointMiddleware(t *testing.T) {
I know this isn't doing much, but I wanted to make sure our middleware is actually executing the wrapped code and attempting to send errors where necessary.

2021-11-29 03:22 UTC, disposedtrolley commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create ca-go/sentry](https://trello.com/c/AFDV26ZB/723-create-ca-go-sentry)

2021-11-29 23:50 UTC, melm73 reviewed
Looks good to me, looks like you're still waiting on answers to your questions, so I won't approve just yet.

2021-11-29 23:50 UTC, melm73 commented on x/sentry/errorreport/middleware.go
> +func NewHTTTPMiddleware(onRequestPanic OnRequestPanicHandler) func(http.Handler) http.Handler {
Typo:  `NewHTTTPMiddleware` has an extra `T`

2021-11-29 23:50 UTC, melm73 commented on x/request/requestids.go
> +type RequestIDs struct {
Nice naming!! 😉

2021-11-29 23:59 UTC, disposedtrolley commented on x/sentry/errorreport/middleware.go
> +func NewHTTTPMiddleware(onRequestPanic OnRequestPanicHandler) func(http.Handler) http.Handler {
https://www.youtube.com/watch?v=3m6Blqs0IgY

2021-12-03 00:10 UTC, jamestelfer requested changes
Most of the comments aren't that high impact IMO. Understanding the required use and getting that in the doco is the biggest thing.

2021-12-03 00:10 UTC, jamestelfer commented on x/sentry/errorreport/middleware_test.go
> +		_, _ = sut(context.Background(), nil)
Anything to assert on these returns?

2021-12-03 00:10 UTC, jamestelfer commented on x/sentry/errorreport/middleware_test.go
> +		_, _ = sut(context.Background(), nil)
And here?

2021-12-03 00:10 UTC, jamestelfer commented on x/sentry/errorreport/middleware_test.go
> +func TestGoaEndpointMiddleware(t *testing.T) {
entirely appropriate

2021-12-03 00:10 UTC, jamestelfer commented on x/sentry/errorreport/middleware.go
> +func NewHTTPMiddleware(onRequestPanic OnRequestPanicHandler) func(http.Handler) http.Handler {
Also, if we implemented this in another context (like a queue), what would be needed? This shouldn't block us merging this PR

2021-12-03 03:08 UTC, disposedtrolley commented on x/sentry/errorreport/errorreport.go
> +	if sentryConfig == nil {
I've updated this to return early if `connected` is already true.

2021-12-03 03:10 UTC, disposedtrolley commented on x/sentry/errorreport/middleware.go
> +	return func(next http.Handler) http.Handler {
Yep, I'll adjust the existing comments to be a bit clearer.

2021-12-03 03:17 UTC, disposedtrolley commented on x/sentry/errorreport/middleware.go
> +func NewHTTPMiddleware(onRequestPanic OnRequestPanicHandler) func(http.Handler) http.Handler {
A good default handler might write a 500 status code with an empty body. Should we include something like this?

```go
func DefaultOnRequestPanicHandler(ctx context.Context, w http.ResponseWriter, err error) {
	w.WriteHeader(http.StatusInternalServerError)
}
```

2021-12-03 03:57 UTC, disposedtrolley commented on x/sentry/errorreport/middleware.go
> +	})
I've added request fields to the Sentry scope in the HTTP middleware too. I've also improved the tests so we augment the context with sample values, and check the values have been propagated in the Sentry error report.

2021-12-03 04:00 UTC, disposedtrolley commented on x/sentry/errorreport/config.go
> +type sentryBeforeFilter func(event *sentry.Event, hint *sentry.EventHint) *sentry.Event
No reason, I think it was private when we were drafting the API and I didn't check to change it.

2021-12-03 04:06 UTC, disposedtrolley commented on x/sentry/errorreport/config.go
> +// This is a mandatory option.
Much better, thanks!

2021-12-03 04:47 UTC, jamestelfer commented on x/sentry/errorreport/middleware.go
> +func NewHTTPMiddleware(onRequestPanic OnRequestPanicHandler) func(http.Handler) http.Handler {
I'd say write a JSON API error by default, with the message "Internal server error" and set the mime type to `application/json`. This is more likely to match what the service is exposing in its API interface

2021-12-03 05:10 UTC, jamestelfer commented on x/sentry/errorreport/middleware.go
> +	// to the client.
```suggestion
	// Returns a handler that configures Sentry to report the panic, and then re-panic.
	//
	// The new panic is recovered to enable the onRequestPanic function to be executed so
	// it can perform further manipulation of the HTTP response before it's sent
	// to the client.
	//
	// The most common action on panic will be to change the HTTP response code
	// and request body to reflect an error occurring.
```

2021-12-03 05:20 UTC, disposedtrolley commented on x/request/doc.go
> +package request
Document usage here for configuration and both middlewares.

2021-12-03 05:21 UTC, disposedtrolley commented on x/sentry/errorreport/doc.go
> +package errorreport
Document usage here for configuration and both middlewares.

2021-12-05 22:57 UTC, disposedtrolley commented on x/sentry/errorreport/errorreport.go
> +func Connect() error {
Collapse this and `Configure` into a single `Init` function.

2021-12-06 03:06 UTC, disposedtrolley commented on x/sentry/errorreport/middleware.go
> +func NewHTTPMiddleware(onRequestPanic OnRequestPanicHandler) func(http.Handler) http.Handler {
I've added a default implementation but have run across some issues with how the panic handler constructs the error response.

1. If the request handler sets the status code prior to panicking, there is no way for the panic handler to re-write the status code to 500.
2. If the request handler writes to the response body prior to panicking, the panic handler will append the JSON:API error response to whatever was written already.

2021-12-06 04:51 UTC, jamestelfer commented on x/sentry/errorreport/doc.go
> +//   mw(myGoaEndpoint)
```suggestion
// Goa middleware can be used:
//   mw := errorreport.NewGoaMiddleware()
//   mw(myGoaEndpoint)
//
// This is recommended when using Goa, as it offers reporting of all errors returned from 
// the generated logic types.
```

2021-12-06 04:52 UTC, jamestelfer commented on x/sentry/errorreport/doc.go
> +//	 }
```suggestion
// if err != nil {
//    // handle initialisation error
// }
```

2021-12-06 05:07 UTC, jamestelfer commented on x/sentry/errorreport/middleware.go
> +func NewHTTPMiddleware(onRequestPanic OnRequestPanicHandler) func(http.Handler) http.Handler {
There are ways to get around both of these, at least in part. For a failed request though, I'm happy with a broken response format -- either way it's broken, adding the additional JSON is the least of their worries.

It's worth noting too that most `panic`-worthy behaviour comes from logic that occurs before writing a response. This means that while the above can occur, the default behaviour that tries to return a reasonable response works better than the default of not doing anything.

2021-12-06 05:09 UTC, jamestelfer commented on x/sentry/errorreport/middleware.go
> +
Note that we'll get these shortly with the API errors package.

2021-12-06 05:09 UTC, jamestelfer commented on x/sentry/errorreport/middleware.go
> +	})
Note that given that there is nothing dynamic in this response, a literal JSON string would work just as well.

2021-12-06 05:11 UTC, jamestelfer requested changes
Minor doco nits, and a note that you're two methods off 100% coverage ;)

2021-12-06 05:22 UTC, disposedtrolley commented on x/sentry/errorreport/middleware.go
> +	})
Yeah I'm inclined to use a literal JSON string instead, until the API errors package arrives in theatres.

2021-12-06 05:38 UTC, disposedtrolley commented on x/sentry/errorreport/middleware.go
> +func NewHTTPMiddleware(onRequestPanic OnRequestPanicHandler) func(http.Handler) http.Handler {
Yep that's what I was thinking too. We should be okay for the majority of cases.

2021-12-07 22:51 UTC, jamestelfer approved these changes
:hype_frog: Let's go!

2021-12-07 22:52 UTC, merged